#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun  5 10:26:00 2023

@author: ishita
"""
    #to start from 99 and to go down to 0, make sure to put (99, 0, -1) in the range so that it won't go from 0 to 99
for x in range(99, 0, -1):
    #curly brackets are for string indentation to identify a block of code, this is NOT string concatenation
    print(f'{x} buckets of candy on the wall, {x} buckets of candy, take one down, pass it around, {x} buckets of candy on the wall')
    
