#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun  5 10:20:20 2023

@author: ishita
"""

#for loop structure: for [any variable] [with]in range 0 to 100, print the string value 100 times
for i in range(100): 
   #think professor umbridge when she made harry repeat "I will not tell lies", although this string can be anything, the project is meant to exemplify detention :)
    print("I will not use my phone in class")
    

