#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun  5 10:05:00 2023

@author: ishita
"""
#assign value to variables guess and tries
#0 because if it has any other value, the program will not output what the user inputs
guess = 0
tries = 0

#while loop structure: while [variable] radical operator value: variable = XXX
while guess != 6:
  guess = int(input("Guess the number:  "))
  tries = tries + 1
  
  #if function to stop the program when tries reaches more than 10
  if tries >= 10: 
      print("You ran out of tries.")
    
    #print to display in console
print("You got it!")


